name = "FortranStrings"
uuid = "fc18e7c4-0b83-4f3c-b75e-a9a8c77010a4"
authors = ["Denis Telnov <denis.telnov@gmail.com> and contributors"]
version = "0.2.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
